name: C++ CI with MSBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 设置中文和Unicode语言环境
      run: |
        chcp 65001  # 设置控制台代码页为UTF-8以支持中文
        set LC_ALL=zh_CN.utf8  # 设置Unicode环境变量为UTF-8
        echo 设置语言环境为中文和Unicode
        
    - name: 检查储存库
      uses: actions/checkout@v4.1.1

    - name: 设置MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: 编译
      run: msbuild /p:Configuration=Release /t:Build /p:WarningLevel=1 /p:nowarn=4566
